#cd /mnt/c/Entwicklung/ansible/influxdb_grafana && ansible-playbook -i hosts influx_grafana.yml --ask-pass --ask-become-pass --user andreas
- name: install influx_grafana
  hosts: local
  become: true
  
  vars:
   home_dir: "/home/andreas"
   
  
  tasks:
  - name: add repo key influxdb
    become: yes
    shell: 
      curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -
  - apt:
    name: influxdb
    state: present
  - service: name=influxdb state=restarted

  - name: Create database
    influxdb_database:
      hostname: "ubuntu"
      database_name: "ultrasonic"
  - name: Create an admin user on a remote host using custom login credentials
    influxdb_user:
      user_name: ultra
      user_password: ultra
      admin: no
      hostname: "ubuntu"
      login_username: "admin"
      login_password: "admin"
  - name: add repo key grafana
    become: yes
    shell: 
      curl https://packages.grafana.com/gpg.key | apt-key add -
# Install grafana
  - apt:
    name: grafana
    state: present
  - service: name=grafana-server state=started
  - name: Make sure grafana-server is running
    systemd: state=started name=grafana-server enabled=true
  - apt:
    name: openjdk-12-jdk
    state: present
  #- name: Download file from a file path
  #  shell:
  #    wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
  - name: create folder
    become: yes
    shell: 
      mkdir -p /opt/gradle
  - apt:
    name: unzip
    state: present
  - apt:
    name: gradle
    state: present
  #- name: update gradle
  #  become: yes
  #  shell: 
  #      add-apt-repository ppa:cwchien/gradle
  #      apt-get update
  #      apt upgrade gradle
  - git:
      repo: 'https://github.com/AndreasD83/rabbit'
      dest: /home/openhabian/springboot_ultrasonic
      force: yes
  - name: gradle build
    become: yes
    shell: 
      cd /home/openhabian/springboot_ultrasonic &&  gradle clean build
  - name: springboot rabbitmq ---> influxdb start
    become: yes
    shell: 
      java -jar /home/openhabian/springboot_ultrasonic/build/libs/rabbitmq-1.0.0-SNAPSHOT.jar --spring.config.location=/home/openhabian/springboot_ultrasonic/src/main/resources/application.properties&
